default:
- 'watch:all'

export-all:
- clean
- text-mate
- dash
- 'shell:reloadDash'

pre-push:
- lint

lint:
- jshint
- 'jsbeautifier:lint'

watch_js:
- jsbeautifier
- lint

watch_snippets:
- export-all

fresh:
- export-all
